### Update profile detail
PUT localhost:8080/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYwIiwic3ViIjoiOTk4OTMxMDUxNzM5IiwiaWF0IjoxNzM3MTk1NDk0LCJleHAiOjE3MzcyODE4OTR9.u5LbDeEbT0Aym-U_DGEV4MeXS-teF2t2U17sLIXhnF_eVj3hGbPAK3OpNZSihx0iYgByGTywkTk-MPSHy18P7A

{
  "name": "Savriddin"
}


### Update password detail
PUT localhost:8080/profile/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYwIiwic3ViIjoiOTk4OTMxMDUxNzM5IiwiaWF0IjoxNzM3MTk1NDk0LCJleHAiOjE3MzcyODE4OTR9.u5LbDeEbT0Aym-U_DGEV4MeXS-teF2t2U17sLIXhnF_eVj3hGbPAK3OpNZSihx0iYgByGTywkTk-MPSHy18P7A

{
  "currentPswd": "111111",
  "newPswd": "123"
}


### Update Username
PUT localhost:8080/profile/username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYwIiwic3ViIjoiOTk4OTMxMDUxNzQ0IiwiaWF0IjoxNzM3MzUyNjQ0LCJleHAiOjE3Mzc0MzkwNDR9.ZbrZPMDjUUSPXIG3o_8orgIgFJdFUmoq-OovLqFb1Gtq6kPqv60PM0-zh5REJrOaE1oNSz7L_goAuWyHWXInAA

{
  "username": "998931051739"
}


### Update Username Confirm
PUT localhost:8080/profile/username/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYwIiwic3ViIjoiOTk4OTMxMDUxNzQ0IiwiaWF0IjoxNzM3MzUyNjQ0LCJleHAiOjE3Mzc0MzkwNDR9.ZbrZPMDjUUSPXIG3o_8orgIgFJdFUmoq-OovLqFb1Gtq6kPqv60PM0-zh5REJrOaE1oNSz7L_goAuWyHWXInAA

{
  "code": "14803"
}


### Update Profile Photo
PUT localhost:8080/profile/photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTYwIiwic3ViIjoiOTk4OTMxMDUxNzM5IiwiaWF0IjoxNzM3MzcyNjMyLCJleHAiOjE3Mzc0NTkwMzJ9.RKO79HWH07elvXjG4aalrNre8u6emjQRzZEyc4evoVnvSspOd4dPg6BXeLfrx5Hopks51R-uyquwG46Na-OcHQ

{
  "photoId": "f6c083bf-181e-46f0-a9fb-796b65b91d30.png"
}


### Profile Filter
POST localhost:8080/profile/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjE1OSIsInN1YiI6ImFiYWhyaWRkaW42N0BnbWFpbC5jb20iLCJpYXQiOjE3NDM4Njg1MjksImV4cCI6MTc0Mzk1NDkyOX0.GZTh5qCk7kxWA1l_cQJiKykX6EKCWJdk9S1MqwmTguk3FbZAhhEENYchegLNBKuE1vhvmH6LkX6NqSW26ArtAQ

{
  "query": "af"
}


### Profile Change Status
PUT localhost:8080/profile/status/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjE1OSIsInN1YiI6ImFiYWhyaWRkaW42N0BnbWFpbC5jb20iLCJpYXQiOjE3NDM4NTM5MDEsImV4cCI6MTc0Mzk0MDMwMX0.oBWW1ki5v3r5qmRC3cIFK2T-iXiLMXnPxlES3gckzHYQXYAZlginy74DU51_0NtqGqAn1R7iFltOXnBRbDc7yw

{
  "status": "ACTIVE"
}


### Profile delete
DELETE localhost:8080/profile/159
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfQURNSU4iLCJpZCI6IjE1OSIsInN1YiI6ImFiYWhyaWRkaW42N0BnbWFpbC5jb20iLCJpYXQiOjE3NDM4NTM5MDEsImV4cCI6MTc0Mzk0MDMwMX0.oBWW1ki5v3r5qmRC3cIFK2T-iXiLMXnPxlES3gckzHYQXYAZlginy74DU51_0NtqGqAn1R7iFltOXnBRbDc7yw